### ISSUE TITLE
Json [Feature]

### ISSUE THREAD

**Issue by Mark7625** [blurite/rscm-plugin#1]
Would it possible to add support for usage from within Json files like so 

![YVG3Ger](https://github.com/user-attachments/assets/ccba2d46-87c4-40b8-8ece-d7e60615fe7c)

**Comment by Z-Kris** [comment]
Not by the Blurite team, but we are open to accepting a PR that would add support for it. It shouldn't be too difficult to add another language to the mix, it just works off of strings and strings are supported by all languages anyhow.

**Comment by Mark7625** [comment]
> Not by the Blurite team, but we are open to accepting a PR that would add support for it. It shouldn't be too difficult to add another language to the mix, it just works off of strings and strings are supported by all languages anyhow.

No worries this is also fine, Ill look into maybe adding it as a option in the settings
